### ISSUE TITLE
✨ Feat. 로그인, 회원가입 일부 통신 연결

### ISSUE THREAD

**Issue by xogk1128** [ShipDoc/Frontend#15]
# 📝 Preview

✨ Feat. 로그인, 회원가입 일부 통신 연결

# ✅ Todo
- [x] 로그인 통신 연결 
- [x] 회원가입 인증하기 제외 통신 연결
- [x] navbar 텍스트 생성

# 📌 Remark
