### ISSUE TITLE
✨ Feat. Chat Layout 구현 일부 기능 추가

### ISSUE THREAD

**Issue by xogk1128** [ShipDoc/Frontend#17]
# 📝 Preview

✨ Feat. Chat Layout 구현 일부 기능 추가

# ✅ Todo
- [x] Chat Layout 구현 
- [x] 회원가입 인증 및 타이머 구현
- [x] NavBar Active 메뉴 적용

# 📌 Remark
