### ISSUE TITLE
✨ Feat. 건강검진 가능 병원 리스트 Layout 구현 및 통신 일부 연결

### ISSUE THREAD

**Issue by xogk1128** [ShipDoc/Frontend#19]
# 📝 Preview

✨ Feat. 건강검진 가능 병원 리스트 Layout 구현 및 통신 일부 연결

# ✅ Todo
- [x] 건강검진 가능 병원 리스트 Layout 구현 
- [x] 로그인/회원가입 통신 완료
- [x] 사용자 좌표를 가져오는 useGeoLocation 훅 생성
- [x] 병원 세부 사항 통신 연결 

# 📌 Remark
