### ISSUE TITLE
✨ Feat. 회원가입 Layout 구현

### ISSUE THREAD

**Issue by xogk1128** [ShipDoc/Frontend#3]
# 📝 Preview

✨ Feat. 회원가입 Layout 구현

# ✅ Todo
- [x] 체크 박스 state 이용해 구현
- [x] 전체 동의시 전체 체크
- [x] 필수 체크시 버튼 활성화

# 📌 Remark
