### ISSUE TITLE
✨ Feat. 회원가입 정보 입력 Layout 구현

### ISSUE THREAD

**Issue by xogk1128** [ShipDoc/Frontend#5]
# 📝 Preview

✨ Feat. 회원가입 정보 입력 Layout 구현

# ✅ Todo
- [x] 유효성 검사 구현
- [x] 인증하기 모달 구현
- [x] 회원가입 완료 화면 구현

# 📌 Remark
