### ISSUE TITLE
✨ Feat. 상세정보 페이지 구현

### ISSUE THREAD

**Issue by xogk1128** [ShipDoc/Frontend#7]
# 📝 Preview

✨ Feat. 상세정보 페이지 구현

# ✅ Todo
- [x] 상세정보 페이지 구현
- [ ] 진료 시간 구현
- [ ] 페이지의 위치 구현

# 📌 Remark
